# Generated by Django 5.2 on 2025-04-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='application_date',
            new_name='date_applied',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_title',
            new_name='position',
        ),
    ]
